config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  #root 'articles#index'
  resources :articles

  # we want to create appath so that /signup will take the users
  # to the new action.  To create the rest, we can simply display
  # resources :users, but exclude the new action.   Or we can
  # handle the post request as shown below.
  # post 'users', to 'users#create'
  #
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  # login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories

  # get 'article', to: 'article#index'
  #get 'welcome/home', to: 'welcome#home'
  #get 'welcome/about', to: 'welcome#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum:25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  # before data is saved, let's set it so that emails
  # are always saved in lowercase.
  before_save { self.email = email.downcase}

  validates :username, presence: true, uniqueness: { case_sensitive: false},
             length: {minimum: 3, maximum: 25}

  # we validate our email using regex
  VALID_EMAIL_REGEX= /\w*\@\w*\.\w*/
  validates :email, presence: true, length: {maximum: 105},
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # methods are availalbe to controllers, but not to views
  # so we need to declare ones we want to use in views as helpers
  helper_method :current_user, :logged_in?

  def current_user
    # return this user if session user_id is stored, then fetch that users
    # from the database, making that user available in the view
    # also miinimize multiple hits to the #
    # ||= is like +=
    # @current_user = @current_user || user.find()...  so we simply return
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # to convert anything to boolean, use !!
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to do this"
      redirect_to root_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # call set_article method before actions, only for actions
  # specified by only:
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_owner, only: [:edit, :update, :destroy]

  #alias_method :select_for_count_with_relation, :select_for_count
  #remove_method :select_for_count

  def index
    #@articles = Article.all
    #@articles = Article.paginate(page: params[:page]) #, per_page: 5)
    @articles = Article.paginate(page: params[:page], per_page: 5)

  end
  def new
    @article = Article.new
    #@article = user.article.build
  end

  #edit
  def edit
    # @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = "Record Not Found"
    redirect_to new_article_path()
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    if @article.destroy
      flash[:warning] = "Article deleted"
      redirect_to articles_path
    end
  end

  #create
  def create
    #render plain: params[:article].inspect
    # whitelist the

    # for debugging we just enter debugger without the comment
    # debugger
    @article = Article.new(article_params)
    @article.user = current_user
    # temp
    #@article.user_id = 7

    #@article.save  # at this point, article is saved but
                   #nothing happens, so we need to show
    #redirect_to article_path(@article)
    if @article.save
      # display message
      flash[:success] = "Article was created!"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  #show
  def show
    #@article = Article.find(params[:id])
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_owner
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit you own"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to category_path(@category)
    else
      render "new"
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    #params.require(:user).permit(:username,:email, :password)
    params.require(:category).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # login
  def new
  end

  # logged in state
  def create
    #render "new"
    #debugger
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # save user id to sessions has which is saved in cookies
      session[:user_id] = user.id
      flash[:success] = "You have succesfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There is something wrong with your info"
      render 'new'
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_owner, only: [:edit, :update, :destroy]
  before_action :require_user, except: [:new, :create]
  before_action :require_admin, only: [:destroy]

  def index
    #@user = User.all
    @user = User.paginate(page: params[:page], per_page: 3)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    # set this user as being logged in after signing up
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Scott's Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    #@articles = @user.articles

    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles have been deleted"
    redirect_to users_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Successfully updated info"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def edit
     @user = User.find(params[:id])
  end

private
  def user_params
    # we need to specify what fields we are permitting - concept called
    # whitelisting.  Prevent mass updating, by only allowing what we
    # permit
    params.require(:user).permit(:username,:email, :password)
  end

  def require_owner
    @user = User.find(params[:id])
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin user can delete"
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_footer.html.erb
<%# only show the back button if current page is  not
    the index page
%>
<div class="row">
  <div class ="well col-sm-3">
    <div class="article-actions">
      <% if current_page?(action: 'index') == false %>
        <%= link_to "Back to Articles", articles_path,
            class: "btn btn-xs btn-secondary" %>
      <% end %>
      <% if current_page?(action: 'show') == true %>
         <%= link_to "Edit this article", edit_article_path(@article),
         class: "btn btn-xs btn-success" if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <% end %>
    </div>
   </div>
</div>

app/views/articles/_form.html.erb
<%# we pass in our articles object to the errors partial so that we
  # reuse it
%>
<%= render 'shared/errors', obj: @article %>

<%#div class='row'%>
  <%#div class='col-xs-12'%>
    <%= form_for @article do |f| %>
       <div class="form-group row">
         <div class="col-sm-2 col-form-label">
           <%= f.label :title %>
         </div>
         <div class="col-sm-10">
           <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
         </div>
       </div>
       <div class="form-group row">
         <div class="col-sm-2 col-form-label">
           <%= f.label :description %>
         </div>
         <div class="col-sm-10">
           <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description" %>
         </div>
       </div>
       <div class="form-group row">
           <div class="col-sm-10">
             <%= f.submit class: "btn btn-primary"%>
           </div>
     </div>
    <% end %>
  <%#/div%>
 <%#/div%>

app/views/articles/_panel.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Collapsible Group Item #2
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Collapsible Group Item #3
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= render 'articles/form' %>

<%= render 'articles/footer' %>

app/views/articles/index.html.erb
<h1> Articles Page - Welcome </h1>
<p><%= link_to "Create New Article", new_article_path,
    class: "btn btn-primary" if logged_in? %></p>

<!--div class="flickr_pagination"-->

<div class="flickr_pagination">
    <%= will_paginate @articles %>
</div>

<table class="table">
  <thead class="thead-light">
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th>UserID</th>
    <th>User</th>
    <th></th>
    <th></th>
  </tr>
</thead>
  <% @articles.each do |a| %>

     <tr>
       <td><%= link_to a.id, article_path(a) %></td>
       <td><%= a.title %></td>
       <td><%= truncate(a.description, length: 100) %></td>
       <td><%= a.user_id %></td>
       <% if a.user.nil? %>
          <td>N/A</td>
       <% else %>
          <td><%= a.user.username %></td>
       <% end %>
       <% if logged_in? && (current_user == a.user || current_user.admin?)%>
         <td><%= link_to "Delete", article_path(a), class: "btn btn-danger btn-sm", method: :delete,
         data: {confirm: "Are you sure you want to delete?"} %></td>
         <td><%= link_to "Edit", edit_article_path(a), class: "btn btn-success btn-sm" %></td>
       <% end %>
     </tr>
  <% end %>

</table>
<div class="flickr_pagination">
    <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1> Create an Article </h1>

<%= render 'articles/form' %>

<%#= render 'articles/panel' %>

app/views/articles/show.html.erb
<h2>Title: <%= @article.title %> </h2>
<div class="row">
  <div class="well col-sm-8 col-sm-offset-0">
    <h4 class="center"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>

  <%#= link_to "Edit this article", edit_article_path(@article) %>
  </div>
</div>
<%= render 'articles/footer' %>

app/views/categories/index.html.erb
<h2> Categories </h2>
<% @categories.each do |c| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li class="article-title">
          <%= link_to "#{c.name}", category_path(c) %></li>
      </div>
    </div>
  </ul>
<% end %>

app/views/categories/new.html.erb
<h2> new category </h2>
<%= render 'shared/errors', obj: @category %>

    <%= form_for @category do |f| %>
       <div class="form-group row">
         <div class="col-sm-2 col-form-label">
           <%= f.label :name %>
         </div>
         <div class="col-sm-10">
           <%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
         </div>
       </div>
       <div class="form-group row">
           <div class="col-sm-10">
             <%# depending on action, we set the text for our button %>
             <%= f.submit "Create Category", class: "btn btn-primary" %>
           </div>
     </div>

    <% end %>

app/views/categories/show.html.erb
<h1> Category Show </h1>
<h2>Category: <%= @category.name %>

app/views/layouts/_debug.html.erb
<br>
<div class="container">
    <div class="alert alert-secondary">
    <strong>Debug Info:</strong><br>
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy Scott Kim
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<%#  &#215 is the 'x' character.
  #  close the message by allowing the user to click on the 'x'
  # the type of message that gets displayed depends on the name passed
  # from the controller e.g., flash[:success] wiill result in class
  # alert alert-success
%>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
  <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
  <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <%= link_to 'Scotts Blog', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
      </li>
      <li class="nav-item">
        <%# <a class="nav-link" href="#">Link1</a> %>
        <%= link_to 'Articles', articles_path, class: 'nav-link' %>
      </li>
      <% if logged_in? %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%# <a class="dropdown-item" href="#">Action</a> %>
          <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
          <%= link_to 'About', about_path, class: 'dropdown-item' %>
          <%= link_to 'Users', users_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <% end %>
        <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile <%= "[Admin]" if current_user.admin? %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%# <a class="dropdown-item" href="#">Action</a> %>
                <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'View Profile', user_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Users', users_path, class: 'dropdown-item' %>

                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link'%></li>
        <% else %>
          <li><%= link_to 'Log in', login_path, class: 'nav-link'%></li>
        <%end %>

        </ul>
    <!-- -
    <form align="right" class="form-inline my-2 my-lg-0">
      <input align="right" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">    
  </head>

  <body>
  <%= render 'layouts/nav'  %>
  <%= render 'layouts/messages' %>
  <div class='container'>
     <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  <!-- turn on development debuggin -->
  <%#= debug(params) if Rails.env.development? %>
  <%= render "layouts/debug" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-0">
      <div class="alert alert-danger" role="alert">
        <h3 class="alert-title">
          <%= pluralize(obj.errors.count, "error") %>
             prohibited this article from being saved:
       </h3>
       <ul>
           <% obj.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
       </ul>
     </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

    <%= form_for @user do |f| %>
       <div class="form-group row">
         <div class="col-sm-2 col-form-label">
           <%= f.label :username %>
         </div>
         <div class="col-sm-10">
           <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
         </div>
       </div>
       <div class="form-group row">
         <div class="col-sm-2 col-form-label">
           <%= f.label :email %>
         </div>
         <div class="col-sm-10">
           <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
         </div>
       </div>

       <div class="form-group row">
         <div class="col-sm-2 col-form-label">
           <%= f.label :password %>
         </div>
         <div class="col-sm-10">
           <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
         </div>
       </div>
       <div class="form-group row">
           <div class="col-sm-10">
             <%# depending on action, we set the text for our button %>
             <%= f.submit current_page?(action: 'new') ? "Sign-Up" : "Update", class: "btn btn-primary" %>
           </div>
     </div>
    <% end %>

app/views/users/edit.html.erb
<h2> Edit Account </h2>

<%= render 'users/form' %>

app/views/users/index.html.erb
<h2> Users </h2>
<div class="flickr_pagination">
    <%= will_paginate @user %>
</div>

<% @user.each do |u| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-8">
        Name: <%= link_to u.username, user_path(u) %>,
        <%= pluralize(u.articles.count, "article") if u.articles %>
      </div>
      <% if (logged_in? and current_user.admin?) and current_user.id != u.id%>
          <li>&nbsp<%= link_to "Delete User", user_path(u), method: :delete,
             data: { confirm: "Are you sure you want to delete user and all articles?"},
             class: "btn btn-danger" %>
          </li>
      <% end %>

    </div>
  </ul>
<% end %>

app/views/users/new.html.erb
<h2> Sign-up </h2>

<%= render 'users/form' %>

app/views/users/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<div class="show-user" style="margin-top:10px">

   <h3>User: <%= @user.username %>
     <small><a href="#" title="User Info" data-toggle="popover"
     data-trigger="hover" data-content="User iD: <%= @user.id %>">[ID]</a></small>

   </h3><hr>
  <h4>Email: <%= @user.email %></h4>
</div>
<hr>
<div class="flickr_pagination">
    <%= will_paginate @articles %>
</div>
<strong> Articles created: </strong>
<!--style="font-size:30px">User:</> <%= @user.username %> -->
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#ID</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>

    </tr>
  </thead>
  <tbody>
    <%# @user.articles.each do |a| %>
    <% @articles.each do |a| %>
      <tr>
        <td><%= link_to a.id, article_path(a)%></td>
        <td><%= a.title %></td>
        <td><%= a.description %></td>
        <td><%= time_ago_in_words(a.created_at) %></td>
        <td><%= time_ago_in_words(a.updated_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--div class="container"-->

<!--/div-->

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>

app/views/welcome/about.html.erb
<h1> Welcome to About - Edited from Lenovo - dev - fix2 - feat1.0</h1>
From ubuntu
dev3-origin-dev
<%= link_to 'Home', root_path %>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-welcome">Scott's blog!</h1>
  <p class="lead text-welcome">Where all the cool people hang out!</p>
  <hr class="my-4 text-welcome">
  <p class="text-welcome">Sign up to start the fun!</p>
  <%# <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a> %>
  <%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg" %>
</div>